<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony"><HintPath>Libs\0Harmony.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="BepInEx"><HintPath>Libs\BepInEx.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>Libs\UnityEngine.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>Libs\UnityEngine.CoreModule.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine.PhysicsModule"><HintPath>Libs\UnityEngine.PhysicsModule.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine.ParticleSystemModule"><HintPath>Libs\UnityEngine.ParticleSystemModule.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="Citruslib"><HintPath>Libs\Citruslib.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="Assembly-CSharp"><HintPath>Libs\Assembly-CSharp.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="Sirenix.Serialization"><HintPath>Libs\Sirenix.Serialization.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="Sirenix.OdinInspector.Attributes"><HintPath>Libs\Sirenix.OdinInspector.Attributes.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="Sirenix.Serialization.Config"><HintPath>Libs\Sirenix.Serialization.Config.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="Sirenix.Utilities"><HintPath>Libs\Sirenix.Utilities.dll</HintPath><Private>False</Private></Reference>
  </ItemGroup>

  <Target Name="CopyCustomGrenadesToBundledPlugins" AfterTargets="Build">
    <MakeDir Directories="$(MSBuildProjectDirectory)\..\bundled\plugins" />
    <MakeDir Directories="$(MSBuildProjectDirectory)\..\bundled\client-plugins" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(MSBuildProjectDirectory)\..\bundled\plugins" SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(MSBuildProjectDirectory)\..\bundled\client-plugins" SkipUnchangedFiles="true" />
  </Target>
</Project>
