using System;
using System.Collections.Generic;
using System.IO;

namespace TabgInstaller.Core
{
    /// <summary>
    /// Built-in server templates for common game modes.
    /// Each template includes all config files needed to run that mode.
    /// </summary>
    public static class BuiltInPresets
    {
        public record BuiltInPreset(string Name, string Description, string Notes, Dictionary<string, string> Files, string[] RequiredPlugins);

        /// <summary>Common plugins needed by DM/GG/Scavenge modes.</summary>
        private static readonly string[] GameModePlugins = { "Citruslib.dll", "StarterPack.dll", "StarterPackFixes.dll", "CustomSpawnpoints.dll", "FreddoTABGCommission.dll" };
        /// <summary>Plugins for standard BR mode.</summary>
        private static readonly string[] BattleRoyalePlugins = { "Citruslib.dll", "MatchAndPreMatchTimeout.dll", "ServerLogger.dll", "VoteToStart.dll" };

        public static readonly IReadOnlyList<BuiltInPreset> All = new List<BuiltInPreset>
        {
            CollinSigma(),
            BattleRoyaleMoreLoot(),
            DeathmatchBigWork(),
            GunGameCastle(),
            ScavengePointOfImpact()
        };

        /// <summary>Deploy a built-in preset by writing all its files and copying required plugins.</summary>
        public static void Deploy(BuiltInPreset preset, string serverDir)
        {
            // Write text config files
            foreach (var (relativePath, content) in preset.Files)
            {
                var dst = Path.Combine(serverDir, relativePath);
                Directory.CreateDirectory(Path.GetDirectoryName(dst)!);
                File.WriteAllText(dst, content);
            }

            // Copy required plugin DLLs
            if (preset.RequiredPlugins.Length > 0)
            {
                var pluginsDir = Path.Combine(serverDir, "BepInEx", "plugins");
                Directory.CreateDirectory(pluginsDir);

                var bundledDir = FindBundledPluginsDir();
                if (bundledDir != null)
                {
                    foreach (var dll in preset.RequiredPlugins)
                    {
                        var src = Path.Combine(bundledDir, dll);
                        var dst = Path.Combine(pluginsDir, dll);
                        if (File.Exists(src))
                            File.Copy(src, dst, overwrite: true);
                    }
                }
            }
        }

        /// <summary>Searches for bundled plugin DLLs directory in known locations.</summary>
        public static string? FindBundledPluginsDir()
        {
            var baseDir = AppDomain.CurrentDomain.BaseDirectory;
            var candidates = new List<string>
            {
                Path.Combine(baseDir, "plugins"),
                Path.Combine(baseDir, "Assets", "bundled", "plugins"),
                Path.Combine(baseDir, "..", "plugins"),
                Path.Combine(baseDir, "..", "..", "plugins"),
                Path.Combine(baseDir, "..", "..", "..", "plugins"),
            };

            // Also search up from base dir for a mods or plugins folder
            var dir = new DirectoryInfo(baseDir);
            while (dir?.Parent != null)
            {
                var modsDir = Path.Combine(dir.FullName, "mods");
                if (Directory.Exists(modsDir)) candidates.Add(modsDir);
                var plugDir = Path.Combine(dir.FullName, "plugins");
                if (Directory.Exists(plugDir)) candidates.Add(plugDir);
                dir = dir.Parent;
            }

            foreach (var c in candidates)
            {
                if (Directory.Exists(c) && Directory.GetFiles(c, "*.dll").Length > 0)
                    return c;
            }
            return null;
        }

        private static readonly string SharedExtraSettings = @"[
  {
    ""name"": ""suppress landlog"",
    ""description"": ""Prevents most landfall debug messages from being written."",
    ""value"": ""False""
  },
  {
    ""name"": ""disable missing command parrot"",
    ""description"": ""Disables the unknown command parrot response when tryping an unknown command"",
    ""value"": ""False""
  },
  {
    ""name"": ""adminfilelocation"",
    ""description"": ""filepath to a FOLDER where you want the PlayerPerms setting to be stored."",
    ""value"": """"
  },
  {
    ""name"": ""loot table location"",
    ""description"": ""The FOLDER that will hold a loottables FOLDER inside of it."",
    ""value"": """"
  }
]";

        static string CfgPath(params string[] parts) => Path.Combine(parts);

        // ──────────────────────────────────────────────
        // CollinSigma — Collin's personal deathmatch config
        // ──────────────────────────────────────────────
        private static BuiltInPreset CollinSigma()
        {
            var gs = @"// game_settings.txt generated by TabgInstaller
// Allowed word list for name / description: https://github.com/landfallgames/tabg-word-list
ServerName=Deathmatch - Big Work
ServerDescription=/n 5 Players To Play /n 20 kills to win
Port=7777
MaxPlayers=20
Relay=true
AutoTeam=false
Password=enormous
CarSpawnRate=0
StripLootByPercentage=0
RingSizes=244, 244, 244
RingSpeeds=0.001, 50, 0.001
UseTimedForceStart=false
ForceStartTime=90
MinPlayersToForceStart=5
PlayersToStart=5
Countdown=500
AllowRespawnMinigame=true
TeamMode=SOLO
GameMode=Battle Royale
AntiCheat=false
LAN=false
AllowSpectating=true
BaseRingTime=200
TimeBeforeFirstRing=70
WeaponDissapearTime=10
BombDefuseTime=5
GroupsToStart=10
KillsToWin=20
RoundsToWin=3
NumberOfLivesPerTeam=inf
MaxNumberOfTeamsAuto=2
SpawnBots=0
UseSouls=0
NoRing=false
UseKicks=true
DEBUG_DEATHMATCH=false
UsePlayFabStats=false
AntiCheatDebugLogging=false
AntiCheatEventLogging=false
BombTime=30
RoundTime=90";

            var loadouts = "AWPS(14,14,17,1):10%303:1,1:255,53:1/" +
                "AK2K(1,0,14):10%151:1,6:255,6:255/" +
                "Mossberg5K(17,13):10%298:1,8:255,70:1,53:1,54:1,259:1/" +
                "Katana(6):10%254:1,119:1/" +
                "BurstGun(12):10%155:1,6:255,6:255,6:255/" +
                "WindUps(13):10%225:1,270:1,270:1,9:255,9:255/" +
                "Big and Melee(4,9):10%261:1,89:1,125:1/" +
                "Money Makers(6):10%234:1,180:1,304:1,304:1,53:1,55:1,9:255,9:255,3:255,3:255/" +
                "Sniper Shotgun:10%225:1,326:1,8:255,112:1,99:1,57:1,28:1/" +
                "M16 and Gauss:10%160:1,6:255,6:255,172:1,2:50,118:1,29:1,38:1/" +
                "Flint and UMP:10%267:1,4:50,314:1,9:255,9:145,117:1,52:1,38:1,29:1/" +
                "Water:10%76:1,185:1,126:1,123:1,12:255,12:255,12:255,12:255,12:255,12:255,12:255,12:255,12:255,255:1/" +
                "Tank with boxing:10%89:1,243:1,238:1,227:1/" +
                "Revolvers and Rock:10%226:1,281:1,281:1,6:255,121:1,50:1/" +
                "AWP Mirage and Tec:10%317:1,1:200,232:1,313:1,9:255,9:45,22:1,40:1,52:1,117:1/" +
                "STG and Missile:10%161:1,6:255,6:145,231:1,24:1,38:1,118:1,45:1/" +
                "Scar and Ballon:10%22:1,24:1,118:1,162:1,6:255,6:145,2:30,164:1/" +
                "FAL G18C and Ballistic:10%286:1,6:255,6:145,271:1,9:255,238:1,24:1,38:1,53:1,43:1/" +
                "MGL:10%203:1,1:255,1:255,122:1,117:1,53:1/" +
                "MP5 and Kar:10%310:1,9:255,1:100,321:1,118:1,47:1,29:1,38:1,38:1/" +
                "M14 and Blunder:10%289:1,6:255,293:1,4:50,38:1,24:1,53:1,108:1/" +
                "Crossbow and MP44:10%163:1,2:150,161:1,6:250,126:1,50:1,38:1,38:1/" +
                "Thomson and Sawed:10%294:1,8:100,307:1,9:255,9:145,31:1,38:1,53:1,43:1/" +
                "Rock and Glue:10%272:1,9:255,9:255,226:1,73:1,99:1,111:1/" +
                "Speed and Pot:10%75:1,75:1,71:1,259:1,232:1/" +
                "BeamAR and Tree:10%154:1,9:255,9:255,236:1,108:1/" +
                "Big Deagle:10%279:1,6:255,53:1,263:1,223:1/" +
                "MiniGun and Knockback:10%178:1,118:1,6:255,6:255,235:1/" +
                "Hammer and Famas:10%157:1,6:255,38:1,251:1,118:1/" +
                "Barret and Baller:10%53:1,38:1,1:255,9:255,283:1,319:1,39:1/" +
                "Bar and Garand:10%218:1,6:255,1:255,118:1,38:1,22:1,287:1/" +
                "Winchester and Shovel:10%1:255,291:1,38:1,22:1,46:1,121:1,261:1/" +
                "Barettas and Hubert:10%248:1,9:255,9:255,264:1,264:1,264:1,264:1,118:1,53:1/" +
                "Tazers and Cleaver:10%244:1,284:1,11:50,53:1,57:1,47:1/" +
                "AA12:10%292:1,8:255,278:1,6:121,115:1,53:1/";

            var sp = $@"RingSettings=Big Work:100%344,0,-656:244/

WinCondition=KillsToWin
KillsToWin=20
ForceKillAtStart=True
DropItemsOnDeath=False
ItemsGiven=131:2,132:2,
Loadouts={loadouts}
HealOnKill=True
HealOnKillAmount=50
CanGoDown=False
CanLockOut=False
ValidSpawnPoints=6,
CustomSpawnPoint=366,130,-646
PercentOfVotes=100
MinNumberOfPlayers=5
TimeToStart=90
SpelldropEnabled=False
MinSpellDropDelay=999
MaxSpellDropDelay=999
SpellDropOffset=999
PreMatchTimeout=120
PeriMatchTimeout=20";

            var commission = @"## Settings file was created by plugin Freddo TABG Commission v1.0.0
## Plugin GUID: FreddoTABGCommission

[Bans]

BanList =

[Curses]

LoadoutCurses = 14,14,17,1/1,0,14/17,13/6/12/13/4,9/6

[GrenadesOnDeath.Attacker]

Enabled = true

Chance = 1

ID = 198

[GrenadesOnDeath.Corpse]

Enabled = true

Chance = 0.2

ID = 186

[Networking]

StreamingDistance = -1

[Player]

Lives = 256
";

            var fixes = @"## Settings file was created by plugin FreddoFixStarterPack v1.0.0
## Plugin GUID: FreddoFixStarterPack

[Fixes]

EnableLootDrops = false
";

            var spawns = @"## Settings file was created by plugin Freddo Custom Spawnpoints v1.0.0
## Plugin GUID: FreddoCustomSpawnpoints

[Spawn]

Spawnpoints =363,-617;341,-638;358,-711;334,-709;313,-683;380,-663;351,-736;288,-709;342,-687;278,-674;284,-626;322,-654";

            var playerPerms = @"[
  {
    ""name"": ""players"",
    ""description"": ""List of players with modified permission level."",
    ""players"": [
      {
        ""name"": ""Freddo"",
        ""epic"": ""0002b33dd4f54c76aa3da0285377ba16"",
        ""permlevel"": 4
      },
      {
        ""name"": ""Jon_ass"",
        ""epic"": ""0002679463fd49ffab724df634f46418"",
        ""permlevel"": 4
      }
    ]
  }
]";

            var files = new Dictionary<string, string>
            {
                ["game_settings.txt"] = gs,
                ["TheStarterPack.txt"] = sp,
                ["PlayerPerms.json"] = playerPerms,
                [Path.Combine("BepInEx", "config", "FreddoTABGCommission.cfg")] = commission,
                [Path.Combine("BepInEx", "config", "FreddoFixStarterPack.cfg")] = fixes,
                [Path.Combine("BepInEx", "config", "FreddoCustomSpawnpoints.cfg")] = spawns,
            };

            return new BuiltInPreset(
                "CollinSigma",
                "Collin's Deathmatch at Big Work. 20 players, 20 kills, password 'enormous'. 33 loadouts with curses, medkits on spawn, grenade on kill. Admins: Freddo & Jon_ass.",
                "Requires plugins: Citruslib, StarterPack, StarterPackFixes, CustomSpawnpoints, FreddoTABGCommission",
                files, GameModePlugins);
        }

        // ──────────────────────────────────────────────
        // Battle Royale - More Loot
        // ──────────────────────────────────────────────
        private static BuiltInPreset BattleRoyaleMoreLoot()
        {
            var gs = @"// game_settings.txt generated by TabgInstaller
// Allowed word list for name / description: https://github.com/landfallgames/tabg-word-list
ServerName=Battle Royale - More Loot
ServerDescription=5 Minute Time - Then Endgame /n Special Loot /n 5 Players to play /n No revive
Port=7777
MaxPlayers=40
Relay=true
AutoTeam=false
Password=
CarSpawnRate=1.0
UseTimedForceStart=true
ForceStartTime=90.0
MinPlayersToForceStart=10
PlayersToStart=5
Countdown=90.0
AllowRespawnMinigame=true
TeamMode=SOLO
GameMode=BattleRoyale
AntiCheat=false";

            // BR uses no StarterPack mods — standard loot-based BR
            var files = new Dictionary<string, string>
            {
                ["game_settings.txt"] = gs,
                [Path.Combine("BepInEx", "config", "CitrusLib", "ExtraSettings.json")] = SharedExtraSettings,
            };

            return new BuiltInPreset(
                "Battle Royale - More Loot",
                "Classic BR with enhanced loot, 40 players, solo. Force start at 5 players. No StarterPack mods.",
                "This mode uses standard BR with custom loot tables. Does NOT use StarterPack, CustomSpawnpoints, or FreddoTABGCommission plugins.",
                files, BattleRoyalePlugins);
        }

        // ──────────────────────────────────────────────
        // Deathmatch - Big Work
        // ──────────────────────────────────────────────
        private static BuiltInPreset DeathmatchBigWork()
        {
            var gs = @"// game_settings.txt generated by TabgInstaller
// Allowed word list for name / description: https://github.com/landfallgames/tabg-word-list
ServerName=Deathmatch - Big Work
ServerDescription=/n 5 Players To Play /n 20 kills to win
Port=7777
MaxPlayers=20
Relay=true
AutoTeam=false
Password=
CarSpawnRate=0.0
StripLootByPercentage=0
RingSizes=244, 244, 244
RingSpeeds=0.001, 50, 0.001
UseTimedForceStart=false
ForceStartTime=90.0
MinPlayersToForceStart=5
PlayersToStart=5
Countdown=90.0
AllowRespawnMinigame=true
TeamMode=SOLO
GameMode=Battle Royale
AntiCheat=false";

            var loadouts = "AWPS:10%303:1,1:255,53:1/" +
                "AK2K:10%151:1,6:255,6:255/" +
                "Mossberg5K:10%298:1,8:255,70:1,53:1,54:1,259:1/" +
                "Katana:10%254:1,119:1/" +
                "BurstGun:10%155:1,6:255,6:255,6:255/" +
                "WindUps:10%225:1,270:1,270:1,9:255,9:255/" +
                "Big and Melee:10%261:1,89:1,125:1/" +
                "Money Makers:10%234:1,180:1,304:1,304:1,53:1,55:1,9:255,9:255,3:255,3:255/" +
                "Sniper Shotgun:10%225:1,326:1,8:255,112:1,99:1,57:1,28:1/" +
                "M16 and Gauss:10%160:1,6:255,6:255,172:1,2:50,118:1,29:1,38:1/" +
                "Flint and UMP:10%267:1,4:50,314:1,9:255,9:145,117:1,52:1,38:1,29:1/" +
                "Water:10%76:1,185:1,126:1,123:1,12:255,12:255,12:255,12:255,12:255,12:255,12:255,12:255,12:255,255:1/" +
                "Tank with boxing:10%89:1,243:1,238:1,227:1/" +
                "Revolvers and Rock:10%226:1,281:1,281:1,6:255,121:1,50:1/" +
                "AWP Mirage and Tec:10%317:1,1:200,232:1,313:1,9:255,9:45,22:1,40:1,52:1,117:1/" +
                "STG and Missile:10%161:1,6:255,6:145,231:1,24:1,38:1,118:1,45:1/" +
                "Scar and Ballon:10%22:1,24:1,118:1,162:1,6:255,6:145,2:30,164:1/" +
                "FAL G18C and Ballistic:10%286:1,6:255,6:145,271:1,9:255,238:1,24:1,38:1,53:1,43:1/" +
                "MGL:10%203:1,1:255,1:255,122:1,117:1,53:1/" +
                "MP5 and Kar:10%310:1,9:255,1:100,321:1,118:1,47:1,29:1,38:1,38:1/" +
                "M14 and Blunder:10%289:1,6:255,293:1,4:50,38:1,24:1,53:1,108:1/" +
                "Crossbow and MP44:10%163:1,2:150,161:1,6:250,126:1,50:1,38:1,38:1/" +
                "Thomson and Sawed:10%294:1,8:100,307:1,9:255,9:145,31:1,38:1,53:1,43:1/" +
                "Rock and Glue:10%272:1,9:255,9:255,226:1,73:1,99:1,111:1/" +
                "Speed and Pot:10%75:1,75:1,71:1,259:1,232:1/" +
                "BeamAR and Tree:10%154:1,9:255,9:255,236:1,108:1/" +
                "Big Deagle:10%279:1,6:255,53:1,263:1,223:1/" +
                "MiniGun and Knockback:10%178:1,118:1,6:255,6:255,235:1/" +
                "Hammer and Famas:10%157:1,6:255,38:1,251:1,118:1/" +
                "Barret and Baller:10%53:1,38:1,1:255,9:255,283:1,319:1,39:1/" +
                "Bar and Garand:10%218:1,6:255,1:255,118:1,38:1,22:1,287:1/" +
                "Winchester and Shovel:10%1:255,291:1,38:1,22:1,46:1,121:1,261:1/" +
                "Barettas and Hubert:10%248:1,9:255,9:255,264:1,264:1,264:1,264:1,118:1,53:1/" +
                "Tazers and Cleaver:10%244:1,284:1,11:50,53:1,57:1,47:1/" +
                "AA12:10%292:1,8:255,278:1,6:121,115:1,53:1/";

            var sp = $@"RingSettings=Big Work:100%344,0,-656:244/

WinCondition=KillsToWin
KillsToWin=20
ForceKillAtStart=true
DropItemsOnDeath=false
ItemsGiven=
Loadouts={loadouts}
HealOnKill=true
HealOnKillAmount=50
CanGoDown=false
CanLockOut=false
ValidSpawnPoints=6
CustomSpawnPoint=366,130,-646
PercentOfVotes=100
MinNumberOfPlayers=5
TimeToStart=90
SpelldropEnabled=false
MinSpellDropDelay=999
MaxSpellDropDelay=999
SpellDropOffset=30
PreMatchTimeout=120
PeriMatchTimeout=20";

            var commission = @"## Settings file was created by plugin Freddo TABG Commission v1.0.0
## Plugin GUID: FreddoTABGCommission

[Bans]

BanList =

[Curses]

LoadoutCurses = 14,14,17,1/1,0,14/17,13/6/12/13/4,9/6

[GrenadesOnDeath.Attacker]

Enabled = true

Chance = 1

ID = 198

[GrenadesOnDeath.Corpse]

Enabled = true

Chance = 0.2

ID = 186

[Networking]

StreamingDistance = -1

[Player]

Lives = 256
";

            var fixes = @"## Settings file was created by plugin FreddoFixStarterPack v1.0.0
## Plugin GUID: FreddoFixStarterPack

[Fixes]

EnableLootDrops = false
";

            var spawns = @"## Settings file was created by plugin Freddo Custom Spawnpoints v1.0.0
## Plugin GUID: FreddoCustomSpawnpoints

[Spawn]

Spawnpoints =363,-617;341,-638;358,-711;334,-709;313,-683;380,-663;351,-736;288,-709;342,-687;278,-674;284,-626;322,-654";

            var files = new Dictionary<string, string>
            {
                ["game_settings.txt"] = gs,
                ["TheStarterPack.txt"] = sp,
                [Path.Combine("BepInEx", "config", "CitrusLib", "ExtraSettings.json")] = SharedExtraSettings,
                [Path.Combine("BepInEx", "config", "FreddoTABGCommission.cfg")] = commission,
                [Path.Combine("BepInEx", "config", "FreddoFixStarterPack.cfg")] = fixes,
                [Path.Combine("BepInEx", "config", "FreddoCustomSpawnpoints.cfg")] = spawns,
            };

            return new BuiltInPreset(
                "Deathmatch - Big Work",
                "FFA Deathmatch at Big Work. 20 players, 20 kills to win, 35 loadouts with curses. Healing grenade on kill, 50% heal. Infinite lives.",
                "Requires plugins: Citruslib, StarterPack, StarterPackFixes, CustomSpawnpoints, FreddoTABGCommission",
                files, GameModePlugins);
        }

        // ──────────────────────────────────────────────
        // Gun Game - Castle
        // ──────────────────────────────────────────────
        private static BuiltInPreset GunGameCastle()
        {
            var gs = @"// game_settings.txt generated by TabgInstaller
// Allowed word list for name / description: https://github.com/landfallgames/tabg-word-list
ServerName=Gun Game - Castle
ServerDescription=/n 5 Players To Play /n 35 kills to win
Port=7777
MaxPlayers=20
Relay=true
AutoTeam=false
Password=
CarSpawnRate=0.0
StripLootByPercentage=0
RingSizes=307, 307, 307
RingSpeeds=0.001, 50, 0.001
UseTimedForceStart=false
ForceStartTime=90.0
MinPlayersToForceStart=5
PlayersToStart=5
Countdown=90.0
AllowRespawnMinigame=true
TeamMode=SOLO
GameMode=Battle Royale
AntiCheat=false";

            var loadouts = "GunGame/" +
                "AK2K47:100%151:1,6:255,6:255,38:1/" +
                "Crossbow:100%169:1,2:255,38:1/" +
                "Barret:100%322:1,1:255,38:1/" +
                "Mossberg5K:100%298:1,8:255/" +
                "Glockinator:100%305:1,9:255,9:255/" +
                "AA12:100%292:1,8:255,38:1/" +
                "Burstgun:100%155:1,6:255,6:255,38:1/" +
                "Missile:100%231:1/" +
                "Blunder:100%293:1,4:255/" +
                "H1:100%158:1,6:255,6:255,38:1/" +
                "AutoCrossbow:100%163:1,2:255,38:1/" +
                "Rainmaker:100%300:1,8:255,38:1/" +
                "UMP:100%314:1,9:255,38:1/" +
                "MG42:100%220:1,6:255,6:255,38:1/" +
                "STG:100%161:1,6:255,38:1/" +
                "AUG:100%153:1,6:255/" +
                "M14:100%289:1,6:255,38:1/" +
                "VSS:100%328:1,9:255,9:255,38:1/" +
                "Garand:100%287:1,1:255,38:1/" +
                "Minigun:100%178:1,6:255,6:255,6:255,6:255/" +
                "MP40:100%309:1,9:255,38:1/" +
                "M16:100%160:1,6:255,38:1/" +
                "Kar98:100%321:1,1:255,38:1/" +
                "CursedFamas:100%157:1,6:255,38:1/" +
                "BeamAR:100%154:1,9:255,9:255/" +
                "Z4:100%316:1,9:255,38:1/" +
                "Deagle:100%279:1,6:255/" +
                "WindUp:100%270:1,9:255/" +
                "Flintlock:100%267:1,4:255/" +
                "Beretta:100%264:1,9:255/" +
                "Tec9:100%313:1,9:255,9:255/" +
                "Holy Revolver:100%281:1,6:255/" +
                "Mac:100%304:1,9:255/" +
                "Luger:100%276:1,9:255/" +
                "Fish:100%248:1/" +
                "Money:100%180:1/";

            var sp = $@"RingSettings=Castle:100%-706,0,544:307/

WinCondition=KillsToWin
KillsToWin=35
ForceKillAtStart=true
DropItemsOnDeath=false
ItemsGiven=
Loadouts={loadouts}
HealOnKill=true
HealOnKillAmount=20
CanGoDown=false
CanLockOut=false
ValidSpawnPoints=6
CustomSpawnPoint=-689,145,510
PercentOfVotes=100
MinNumberOfPlayers=5
TimeToStart=90
SpelldropEnabled=false
MinSpellDropDelay=999
MaxSpellDropDelay=999
SpellDropOffset=30
PreMatchTimeout=120
PeriMatchTimeout=30";

            var commission = @"## Settings file was created by plugin Freddo TABG Commission v1.0.0
## Plugin GUID: FreddoTABGCommission

[Bans]

BanList =

[Curses]

LoadoutCurses =

[GrenadesOnDeath.Attacker]

Enabled = false

Chance = 0.2

ID = 198

[GrenadesOnDeath.Corpse]

Enabled = false

Chance = 0.2

ID = 198

[Networking]

StreamingDistance = -1

[Player]

Lives = 256
";

            var fixes = @"## Settings file was created by plugin FreddoFixStarterPack v1.0.0
## Plugin GUID: FreddoFixStarterPack

[Fixes]

EnableLootDrops = false
";

            var spawns = @"## Settings file was created by plugin Freddo Custom Spawnpoints v1.0.0
## Plugin GUID: FreddoCustomSpawnpoints

[Spawn]

Spawnpoints =-702,502;-725,522;-713,572;-710,536;-697,568;-683,543;-692,549;-691,523;-667,532;-671,550;-656,527;-688,568";

            var files = new Dictionary<string, string>
            {
                ["game_settings.txt"] = gs,
                ["TheStarterPack.txt"] = sp,
                [Path.Combine("BepInEx", "config", "CitrusLib", "ExtraSettings.json")] = SharedExtraSettings,
                [Path.Combine("BepInEx", "config", "FreddoTABGCommission.cfg")] = commission,
                [Path.Combine("BepInEx", "config", "FreddoFixStarterPack.cfg")] = fixes,
                [Path.Combine("BepInEx", "config", "FreddoCustomSpawnpoints.cfg")] = spawns,
            };

            return new BuiltInPreset(
                "Gun Game - Castle",
                "Progressive Gun Game at Castle. 20 players, 35 kills. Weapon advances on each kill. 20% heal on kill. Infinite lives.",
                "Requires plugins: Citruslib, StarterPack, StarterPackFixes, CustomSpawnpoints, FreddoTABGCommission",
                files, GameModePlugins);
        }

        // ──────────────────────────────────────────────
        // Scavenge - Point Of Impact
        // ──────────────────────────────────────────────
        private static BuiltInPreset ScavengePointOfImpact()
        {
            var gs = @"// game_settings.txt generated by TabgInstaller
// Allowed word list for name / description: https://github.com/landfallgames/tabg-word-list
ServerName=Scavenge - Point Of Impact
ServerDescription=/n 5 Players To Play /n 25 kills to win
Port=7777
MaxPlayers=20
Relay=true
AutoTeam=false
Password=
CarSpawnRate=1.0
UseTimedForceStart=false
RingSizes=370, 370, 370
RingSpeeds=0.001, 0.6, 0.001
ForceStartTime=90.0
MinPlayersToForceStart=5
PlayersToStart=5
Countdown=90.0
AllowRespawnMinigame=true
TeamMode=SOLO
GameMode=BattleRoyale
AntiCheat=false";

            var loadouts = "KeepInventory/Ammo and Medkits:100%1:50,2:80,4:50,6:255,6:245,8:100,9:255,9:245,11:10,132:3/";

            var sp = $@"RingSettings=POI:100%-78,0,566:370/

WinCondition=KillsToWin
KillsToWin=25
ForceKillAtStart=false
DropItemsOnDeath=false
ItemsGiven=
Loadouts={loadouts}
HealOnKill=true
HealOnKillAmount=50
CanGoDown=false
CanLockOut=false
ValidSpawnPoints=6
CustomSpawnPoint=-74,125,611
PercentOfVotes=100
MinNumberOfPlayers=5
TimeToStart=90
SpelldropEnabled=true
MinSpellDropDelay=180
MaxSpellDropDelay=420
SpellDropOffset=30
PreMatchTimeout=120
PeriMatchTimeout=30";

            var commission = @"## Settings file was created by plugin Freddo TABG Commission v1.0.0
## Plugin GUID: FreddoTABGCommission

[Bans]

BanList =

[Curses]

LoadoutCurses =

[GrenadesOnDeath.Attacker]

Enabled = false

Chance = 0.2

ID = 198

[GrenadesOnDeath.Corpse]

Enabled = false

Chance = 0.2

ID = 198

[Networking]

StreamingDistance = -1

[Player]

Lives = 256
";

            var fixes = @"## Settings file was created by plugin FreddoFixStarterPack v1.0.0
## Plugin GUID: FreddoFixStarterPack

[Fixes]

EnableLootDrops = true
";

            var spawns = @"## Settings file was created by plugin Freddo Custom Spawnpoints v1.0.0
## Plugin GUID: FreddoCustomSpawnpoints

[Spawn]

Spawnpoints =-41,540;-5,550;-1,589;-31,625;-47,600;-72,634;-90,600;-129,602;-92,559;-125,541;-71,519;-50,559;27,554";

            var files = new Dictionary<string, string>
            {
                ["game_settings.txt"] = gs,
                ["TheStarterPack.txt"] = sp,
                [Path.Combine("BepInEx", "config", "CitrusLib", "ExtraSettings.json")] = SharedExtraSettings,
                [Path.Combine("BepInEx", "config", "FreddoTABGCommission.cfg")] = commission,
                [Path.Combine("BepInEx", "config", "FreddoFixStarterPack.cfg")] = fixes,
                [Path.Combine("BepInEx", "config", "FreddoCustomSpawnpoints.cfg")] = spawns,
            };

            return new BuiltInPreset(
                "Scavenge - Point Of Impact",
                "KeepInventory scavenge at Point Of Impact. 20 players, 25 kills. Items persist through death. Loot drops enabled. 50% heal on kill. Infinite lives.",
                "Requires plugins: Citruslib, StarterPack, StarterPackFixes, CustomSpawnpoints, FreddoTABGCommission",
                files, GameModePlugins);
        }
    }
}
