//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabgInstaller.Gui.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TabgInstaller.Gui.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Admins saved. Restart server to apply changes..
        /// </summary>
        public static string AdminsSaved {
            get {
                return ResourceManager.GetString("AdminsSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backup created successfully!.
        /// </summary>
        public static string BackupCreatedSuccess {
            get {
                return ResourceManager.GetString("BackupCreatedSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backup restored successfully!.
        /// </summary>
        public static string BackupRestoredSuccess {
            get {
                return ResourceManager.GetString("BackupRestoredSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backup deleted successfully!.
        /// </summary>
        public static string BackupDeletedSuccess {
            get {
                return ResourceManager.GetString("BackupDeletedSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installation completed!.
        /// </summary>
        public static string InstallationCompleted {
            get {
                return ResourceManager.GetString("InstallationCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sigma Mode completed successfully!.
        /// </summary>
        public static string SigmaModeCompleted {
            get {
                return ResourceManager.GetString("SigmaModeCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log exported to {0}.
        /// </summary>
        public static string LogExportedTo {
            get {
                return ResourceManager.GetString("LogExportedTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Added server: {0}.
        /// </summary>
        public static string AddedServer {
            get {
                return ResourceManager.GetString("AddedServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select or type a player name..
        /// </summary>
        public static string SelectOrTypePlayer {
            get {
                return ResourceManager.GetString("SelectOrTypePlayer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter both a name and an Epic ID..
        /// </summary>
        public static string EnterNameAndEpicId {
            get {
                return ResourceManager.GetString("EnterNameAndEpicId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No server directory configured..
        /// </summary>
        public static string NoServerDirectory {
            get {
                return ResourceManager.GetString("NoServerDirectory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run Initial Setup first..
        /// </summary>
        public static string RunInitialSetupFirst {
            get {
                return ResourceManager.GetString("RunInitialSetupFirst", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid TABG Steam folder path..
        /// </summary>
        public static string EnterValidTabgPath {
            get {
                return ResourceManager.GetString("EnterValidTabgPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No modded folder path set..
        /// </summary>
        public static string NoModdedFolderPath {
            get {
                return ResourceManager.GetString("NoModdedFolderPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Client setup failed..
        /// </summary>
        public static string ClientSetupFailed {
            get {
                return ResourceManager.GetString("ClientSetupFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run Initial Setup first to create the modded TABG copy..
        /// </summary>
        public static string RunInitialSetupCopy {
            get {
                return ResourceManager.GetString("RunInitialSetupCopy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Modded TABG not found. Run Initial Setup first..
        /// </summary>
        public static string ModdedTabgNotFound {
            get {
                return ResourceManager.GetString("ModdedTabgNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to game_settings.txt not found..
        /// </summary>
        public static string GameSettingsNotFound {
            get {
                return ResourceManager.GetString("GameSettingsNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Client mods not set up..
        /// </summary>
        public static string ClientModsNotSetUp {
            get {
                return ResourceManager.GetString("ClientModsNotSetUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Modded TABG not found. Install client mods first..
        /// </summary>
        public static string ModdedTabgNotFoundClient {
            get {
                return ResourceManager.GetString("ModdedTabgNotFoundClient", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a valid TABG server folder..
        /// </summary>
        public static string SelectValidTabgFolder {
            get {
                return ResourceManager.GetString("SelectValidTabgFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CitrusLib tag is required if not skipping the plugin..
        /// </summary>
        public static string CitruslibTagRequired {
            get {
                return ResourceManager.GetString("CitruslibTagRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installation cancelled..
        /// </summary>
        public static string InstallationCancelled {
            get {
                return ResourceManager.GetString("InstallationCancelled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server path is not set..
        /// </summary>
        public static string ServerPathNotSet {
            get {
                return ResourceManager.GetString("ServerPathNotSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No text entered..
        /// </summary>
        public static string NoTextEntered {
            get {
                return ResourceManager.GetString("NoTextEntered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No server directory set..
        /// </summary>
        public static string NoServerDirectorySet {
            get {
                return ResourceManager.GetString("NoServerDirectorySet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a template to apply..
        /// </summary>
        public static string SelectTemplate {
            get {
                return ResourceManager.GetString("SelectTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a preset to load..
        /// </summary>
        public static string SelectPresetToLoad {
            get {
                return ResourceManager.GetString("SelectPresetToLoad", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a preset to delete..
        /// </summary>
        public static string SelectPresetToDelete {
            get {
                return ResourceManager.GetString("SelectPresetToDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot remove the last server instance..
        /// </summary>
        public static string CannotRemoveLastServer {
            get {
                return ResourceManager.GetString("CannotRemoveLastServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sigma Mode completed with issues..
        /// </summary>
        public static string SigmaModeIssues {
            get {
                return ResourceManager.GetString("SigmaModeIssues", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to create backup..
        /// </summary>
        public static string FailedToCreateBackup {
            get {
                return ResourceManager.GetString("FailedToCreateBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to restore backup..
        /// </summary>
        public static string FailedToRestoreBackup {
            get {
                return ResourceManager.GetString("FailedToRestoreBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to delete backup..
        /// </summary>
        public static string FailedToDeleteBackup {
            get {
                return ResourceManager.GetString("FailedToDeleteBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string ErrorPrefix {
            get {
                return ResourceManager.GetString("ErrorPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to start: {0}.
        /// </summary>
        public static string FailedToStart {
            get {
                return ResourceManager.GetString("FailedToStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to restart: {0}.
        /// </summary>
        public static string FailedToRestart {
            get {
                return ResourceManager.GetString("FailedToRestart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to export log: {0}.
        /// </summary>
        public static string FailedToExportLog {
            get {
                return ResourceManager.GetString("FailedToExportLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to toggle plugin: {0}.
        /// </summary>
        public static string FailedToTogglePlugin {
            get {
                return ResourceManager.GetString("FailedToTogglePlugin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to install {0}: {1}.
        /// </summary>
        public static string FailedToInstallPlugin {
            get {
                return ResourceManager.GetString("FailedToInstallPlugin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to remove plugin: {0}.
        /// </summary>
        public static string FailedToRemovePlugin {
            get {
                return ResourceManager.GetString("FailedToRemovePlugin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to add plugin: {0}.
        /// </summary>
        public static string FailedToAddPlugin {
            get {
                return ResourceManager.GetString("FailedToAddPlugin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to toggle mod: {0}.
        /// </summary>
        public static string FailedToToggleMod {
            get {
                return ResourceManager.GetString("FailedToToggleMod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to launch: {0}.
        /// </summary>
        public static string FailedToLaunch {
            get {
                return ResourceManager.GetString("FailedToLaunch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save failed: {0}.
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not open file: {0}.
        /// </summary>
        public static string CouldNotOpenFile {
            get {
                return ResourceManager.GetString("CouldNotOpenFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error loading plugins: {0}.
        /// </summary>
        public static string ErrorLoadingPlugins {
            get {
                return ResourceManager.GetString("ErrorLoadingPlugins", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installation ended with code {0}..
        /// </summary>
        public static string InstallationEndedWithCode {
            get {
                return ResourceManager.GetString("InstallationEndedWithCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installation error: {0}.
        /// </summary>
        public static string InstallationError {
            get {
                return ResourceManager.GetString("InstallationError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sigma Mode error: {0}.
        /// </summary>
        public static string SigmaModeError {
            get {
                return ResourceManager.GetString("SigmaModeError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The path '{0}' does not exist..
        /// </summary>
        public static string PathDoesNotExist {
            get {
                return ResourceManager.GetString("PathDoesNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restore error: {0}.
        /// </summary>
        public static string RestoreError {
            get {
                return ResourceManager.GetString("RestoreError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to save admins: {0}.
        /// </summary>
        public static string AdminSaveFailed {
            get {
                return ResourceManager.GetString("AdminSaveFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All changes saved.
        /// </summary>
        public static string AllChangesSaved {
            get {
                return ResourceManager.GetString("AllChangesSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings reloaded from file.
        /// </summary>
        public static string SettingsReloaded {
            get {
                return ResourceManager.GetString("SettingsReloaded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings saved to file.
        /// </summary>
        public static string SettingsSavedToFile {
            get {
                return ResourceManager.GetString("SettingsSavedToFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings saved..
        /// </summary>
        public static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings loaded..
        /// </summary>
        public static string SettingsLoaded {
            get {
                return ResourceManager.GetString("SettingsLoaded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating backup....
        /// </summary>
        public static string CreatingBackup {
            get {
                return ResourceManager.GetString("CreatingBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backup failed..
        /// </summary>
        public static string BackupFailed {
            get {
                return ResourceManager.GetString("BackupFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restore failed..
        /// </summary>
        public static string RestoreFailed {
            get {
                return ResourceManager.GetString("RestoreFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preparing....
        /// </summary>
        public static string Preparing {
            get {
                return ResourceManager.GetString("Preparing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restore backup '{0}'?.
        /// </summary>
        public static string ConfirmRestore {
            get {
                return ResourceManager.GetString("ConfirmRestore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm Restore.
        /// </summary>
        public static string ConfirmRestoreTitle {
            get {
                return ResourceManager.GetString("ConfirmRestoreTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete backup '{0}'?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove {0}?.
        /// </summary>
        public static string ConfirmRemove {
            get {
                return ResourceManager.GetString("ConfirmRemove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WARNING: Installation will modify server files!.
        /// </summary>
        public static string InstallationWarning {
            get {
                return ResourceManager.GetString("InstallationWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installation Warning.
        /// </summary>
        public static string InstallationWarningTitle {
            get {
                return ResourceManager.GetString("InstallationWarningTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Modded copy already exists at:.
        /// </summary>
        public static string InitialClientSetupExisting {
            get {
                return ResourceManager.GetString("InitialClientSetupExisting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This will copy TABG to:.
        /// </summary>
        public static string InitialClientSetupNew {
            get {
                return ResourceManager.GetString("InitialClientSetupNew", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Initial Client Setup.
        /// </summary>
        public static string InitialClientSetupTitle {
            get {
                return ResourceManager.GetString("InitialClientSetupTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TABG Manager Error.
        /// </summary>
        public static string TabgManagerError {
            get {
                return ResourceManager.GetString("TabgManagerError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TABG Manager.
        /// </summary>
        public static string TabgManager {
            get {
                return ResourceManager.GetString("TabgManager", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Startup error: {0}.
        /// </summary>
        public static string StartupError {
            get {
                return ResourceManager.GetString("StartupError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found {0} known players ({1} new).
        /// </summary>
        public static string FoundKnownPlayers {
            get {
                return ResourceManager.GetString("FoundKnownPlayers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} admin(s).
        /// </summary>
        public static string LoadedAdmins {
            get {
                return ResourceManager.GetString("LoadedAdmins", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error loading: {0}.
        /// </summary>
        public static string ErrorLoading {
            get {
                return ResourceManager.GetString("ErrorLoading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Player '{0}' not found in Guestbooks..
        /// </summary>
        public static string PlayerNotFound {
            get {
                return ResourceManager.GetString("PlayerNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to '{0}' is already an admin..
        /// </summary>
        public static string AlreadyAdmin {
            get {
                return ResourceManager.GetString("AlreadyAdmin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Added {0}.
        /// </summary>
        public static string AddedPlayer {
            get {
                return ResourceManager.GetString("AddedPlayer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Added {0} (manual).
        /// </summary>
        public static string AddedManual {
            get {
                return ResourceManager.GetString("AddedManual", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Removed {0}.
        /// </summary>
        public static string RemovedPlayer {
            get {
                return ResourceManager.GetString("RemovedPlayer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saved {0} admin(s).
        /// </summary>
        public static string SavedAdmins {
            get {
                return ResourceManager.GetString("SavedAdmins", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scanned Guestbooks.
        /// </summary>
        public static string ScannedGuestbooks {
            get {
                return ResourceManager.GetString("ScannedGuestbooks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to List of players with modified permission level..
        /// </summary>
        public static string AdminJsonDescription {
            get {
                return ResourceManager.GetString("AdminJsonDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restoring '{0}'....
        /// </summary>
        public static string RestoringBackup {
            get {
                return ResourceManager.GetString("RestoringBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restored '{0}'..
        /// </summary>
        public static string RestoredBackup {
            get {
                return ResourceManager.GetString("RestoredBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} backup(s).
        /// </summary>
        public static string BackupCount {
            get {
                return ResourceManager.GetString("BackupCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installed {0} plugin(s)..
        /// </summary>
        public static string InstalledPluginCount {
            get {
                return ResourceManager.GetString("InstalledPluginCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installed {0} mod(s)..
        /// </summary>
        public static string InstalledModCount {
            get {
                return ResourceManager.GetString("InstalledModCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installation cancelled by user..
        /// </summary>
        public static string InstallationCancelledByUser {
            get {
                return ResourceManager.GetString("InstallationCancelledByUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warning: Backup failed -- continuing anyway..
        /// </summary>
        public static string BackupWarningContinuing {
            get {
                return ResourceManager.GetString("BackupWarningContinuing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Applied location: {0}.
        /// </summary>
        public static string AppliedLocation {
            get {
                return ResourceManager.GetString("AppliedLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Applied deathmatch ring preset..
        /// </summary>
        public static string AppliedDeathmatch {
            get {
                return ResourceManager.GetString("AppliedDeathmatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Applied standard BR ring preset..
        /// </summary>
        public static string AppliedStandardBR {
            get {
                return ResourceManager.GetString("AppliedStandardBR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} spawn point(s).
        /// </summary>
        public static string SpawnPointCount {
            get {
                return ResourceManager.GetString("SpawnPointCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto-save failed: {0}.
        /// </summary>
        public static string AutoSaveFailed {
            get {
                return ResourceManager.GetString("AutoSaveFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error saving: {0}.
        /// </summary>
        public static string ErrorSaving {
            get {
                return ResourceManager.GetString("ErrorSaving", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [INFO] Server does not accept stdin commands..
        /// </summary>
        public static string ServerNoStdin {
            get {
                return ResourceManager.GetString("ServerNoStdin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Incorrect password..
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password correct. Enter Sigma mode?.
        /// </summary>
        public static string PasswordCorrectPrompt {
            get {
                return ResourceManager.GetString("PasswordCorrectPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Super Secret.
        /// </summary>
        public static string SuperSecretTitle {
            get {
                return ResourceManager.GetString("SuperSecretTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starting Sigma Mode....
        /// </summary>
        public static string StartingSigma {
            get {
                return ResourceManager.GetString("StartingSigma", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Playing Music....
        /// </summary>
        public static string PlayingMusic {
            get {
                return ResourceManager.GetString("PlayingMusic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Launching TABG....
        /// </summary>
        public static string LaunchingTabg {
            get {
                return ResourceManager.GetString("LaunchingTabg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Setting Fans....
        /// </summary>
        public static string SettingFans {
            get {
                return ResourceManager.GetString("SettingFans", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating Overlays....
        /// </summary>
        public static string CreatingOverlays {
            get {
                return ResourceManager.GetString("CreatingOverlays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scanning for TABG....
        /// </summary>
        public static string ScanningForTabg {
            get {
                return ResourceManager.GetString("ScanningForTabg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Music and black screen active. Waiting for TABG to reach main menu....
        /// </summary>
        public static string WaitingForMainMenu {
            get {
                return ResourceManager.GetString("WaitingForMainMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TABG Loading....
        /// </summary>
        public static string TabgLoading {
            get {
                return ResourceManager.GetString("TabgLoading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TABG process started! Waiting for main menu to load....
        /// </summary>
        public static string TabgProcessStarted {
            get {
                return ResourceManager.GetString("TabgProcessStarted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TABG Window Found....
        /// </summary>
        public static string TabgWindowFound {
            get {
                return ResourceManager.GetString("TabgWindowFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TABG window visible! Waiting for main menu....
        /// </summary>
        public static string TabgWindowVisible {
            get {
                return ResourceManager.GetString("TabgWindowVisible", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Main Menu Ready!.
        /// </summary>
        public static string MainMenuReady {
            get {
                return ResourceManager.GetString("MainMenuReady", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TABG main menu loaded! Stopping Sigma Mode....
        /// </summary>
        public static string TabgMainMenuLoaded {
            get {
                return ResourceManager.GetString("TabgMainMenuLoaded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Force Stopping....
        /// </summary>
        public static string ForceStoppingLabel {
            get {
                return ResourceManager.GetString("ForceStoppingLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Force stopping Sigma Mode....
        /// </summary>
        public static string ForceStopping {
            get {
                return ResourceManager.GetString("ForceStopping", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Crash report sent. Thank you!.
        /// </summary>
        public static string CrashReportSent {
            get {
                return ResourceManager.GetString("CrashReportSent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not send crash report..
        /// </summary>
        public static string CrashReportFailed {
            get {
                return ResourceManager.GetString("CrashReportFailed", resourceCulture);
            }
        }
    }
}
