//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabgInstaller.Gui.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TabgInstaller.Gui.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TABG Manager.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TABG Server Installer.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string TabDashboard {
            get {
                return ResourceManager.GetString("TabDashboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server Mods.
        /// </summary>
        public static string TabServerMods {
            get {
                return ResourceManager.GetString("TabServerMods", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Client Mods.
        /// </summary>
        public static string TabClientMods {
            get {
                return ResourceManager.GetString("TabClientMods", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string TabConfig {
            get {
                return ResourceManager.GetString("TabConfig", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string TabConsole {
            get {
                return ResourceManager.GetString("TabConsole", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backups.
        /// </summary>
        public static string TabBackups {
            get {
                return ResourceManager.GetString("TabBackups", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string TabReference {
            get {
                return ResourceManager.GetString("TabReference", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TabSettings {
            get {
                return ResourceManager.GetString("TabSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to INSTALL.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server Status.
        /// </summary>
        public static string ServerStatus {
            get {
                return ResourceManager.GetString("ServerStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to   STOPPED.
        /// </summary>
        public static string StatusStopped {
            get {
                return ResourceManager.GetString("StatusStopped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to   RUNNING.
        /// </summary>
        public static string StatusRunning {
            get {
                return ResourceManager.GetString("StatusRunning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start Server.
        /// </summary>
        public static string StartServer {
            get {
                return ResourceManager.GetString("StartServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop Server.
        /// </summary>
        public static string StopServer {
            get {
                return ResourceManager.GetString("StopServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Launch Modded TABG.
        /// </summary>
        public static string LaunchModdedTabg {
            get {
                return ResourceManager.GetString("LaunchModdedTabg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quick Actions.
        /// </summary>
        public static string QuickActions {
            get {
                return ResourceManager.GetString("QuickActions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Server Folder.
        /// </summary>
        public static string OpenServerFolder {
            get {
                return ResourceManager.GetString("OpenServerFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Logs.
        /// </summary>
        public static string OpenLogs {
            get {
                return ResourceManager.GetString("OpenLogs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Config Files.
        /// </summary>
        public static string OpenConfigFiles {
            get {
                return ResourceManager.GetString("OpenConfigFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Console Preview (last 20 lines).
        /// </summary>
        public static string ConsolePreview {
            get {
                return ResourceManager.GetString("ConsolePreview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Full Console.
        /// </summary>
        public static string OpenFullConsole {
            get {
                return ResourceManager.GetString("OpenFullConsole", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear Console.
        /// </summary>
        public static string ClearConsole {
            get {
                return ResourceManager.GetString("ClearConsole", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quick-save &amp; Restart.
        /// </summary>
        public static string QuickSaveRestart {
            get {
                return ResourceManager.GetString("QuickSaveRestart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string FilterInfo {
            get {
                return ResourceManager.GetString("FilterInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warn.
        /// </summary>
        public static string FilterWarn {
            get {
                return ResourceManager.GetString("FilterWarn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string FilterError {
            get {
                return ResourceManager.GetString("FilterError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search logs....
        /// </summary>
        public static string SearchLogs {
            get {
                return ResourceManager.GetString("SearchLogs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server Settings.
        /// </summary>
        public static string ServerSettings {
            get {
                return ResourceManager.GetString("ServerSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open in Notepad.
        /// </summary>
        public static string OpenInNotepad {
            get {
                return ResourceManager.GetString("OpenInNotepad", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Match Settings.
        /// </summary>
        public static string MatchSettings {
            get {
                return ResourceManager.GetString("MatchSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ring &amp; Spawns.
        /// </summary>
        public static string RingAndSpawns {
            get {
                return ResourceManager.GetString("RingAndSpawns", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loadouts.
        /// </summary>
        public static string Loadouts {
            get {
                return ResourceManager.GetString("Loadouts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mod Settings.
        /// </summary>
        public static string ModSettings {
            get {
                return ResourceManager.GetString("ModSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Admins.
        /// </summary>
        public static string Admins {
            get {
                return ResourceManager.GetString("Admins", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Presets.
        /// </summary>
        public static string Presets {
            get {
                return ResourceManager.GetString("Presets", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server Plugins.
        /// </summary>
        public static string ServerPlugins {
            get {
                return ResourceManager.GetString("ServerPlugins", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add, remove, or toggle server plugins -- no reinstall needed..
        /// </summary>
        public static string ServerPluginsSubtitle {
            get {
                return ResourceManager.GetString("ServerPluginsSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installed Plugins (BepInEx/plugins).
        /// </summary>
        public static string InstalledPlugins {
            get {
                return ResourceManager.GetString("InstalledPlugins", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add DLL file....
        /// </summary>
        public static string AddDllFile {
            get {
                return ResourceManager.GetString("AddDllFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove Selected.
        /// </summary>
        public static string RemoveSelected {
            get {
                return ResourceManager.GetString("RemoveSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Available Plugins.
        /// </summary>
        public static string AvailablePlugins {
            get {
                return ResourceManager.GetString("AvailablePlugins", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All plugins are already installed..
        /// </summary>
        public static string AllPluginsInstalled {
            get {
                return ResourceManager.GetString("AllPluginsInstalled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Install Selected.
        /// </summary>
        public static string InstallSelected {
            get {
                return ResourceManager.GetString("InstallSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add, remove, or toggle client mods -- same UX as server mods..
        /// </summary>
        public static string ClientModsSubtitle {
            get {
                return ResourceManager.GetString("ClientModsSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paths.
        /// </summary>
        public static string Paths {
            get {
                return ResourceManager.GetString("Paths", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TABG Steam folder:.
        /// </summary>
        public static string TabgSteamFolder {
            get {
                return ResourceManager.GetString("TabgSteamFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Modded copy folder:.
        /// </summary>
        public static string ModdedCopyFolder {
            get {
                return ResourceManager.GetString("ModdedCopyFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installed Client Mods.
        /// </summary>
        public static string InstalledClientMods {
            get {
                return ResourceManager.GetString("InstalledClientMods", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No modded TABG found. Set up paths and click 'Initial Setup' first..
        /// </summary>
        public static string NoModdedTabgFound {
            get {
                return ResourceManager.GetString("NoModdedTabgFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Initial Setup (copy TABG + BepInEx).
        /// </summary>
        public static string InitialSetup {
            get {
                return ResourceManager.GetString("InitialSetup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Available Mods.
        /// </summary>
        public static string AvailableMods {
            get {
                return ResourceManager.GetString("AvailableMods", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All client mods are already installed..
        /// </summary>
        public static string AllClientModsInstalled {
            get {
                return ResourceManager.GetString("AllClientModsInstalled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LAUNCH MODDED TABG.
        /// </summary>
        public static string LaunchModdedTabgCaps {
            get {
                return ResourceManager.GetString("LaunchModdedTabgCaps", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Modded Folder.
        /// </summary>
        public static string OpenModdedFolder {
            get {
                return ResourceManager.GetString("OpenModdedFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage server backups.
        /// </summary>
        public static string ManageBackups {
            get {
                return ResourceManager.GetString("ManageBackups", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Backup.
        /// </summary>
        public static string CreateBackup {
            get {
                return ResourceManager.GetString("CreateBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating....
        /// </summary>
        public static string Creating {
            get {
                return ResourceManager.GetString("Creating", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No backups found..
        /// </summary>
        public static string NoBackupsFound {
            get {
                return ResourceManager.GetString("NoBackupsFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server Admins.
        /// </summary>
        public static string ServerAdmins {
            get {
                return ResourceManager.GetString("ServerAdmins", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Perm Level.
        /// </summary>
        public static string PermLevel {
            get {
                return ResourceManager.GetString("PermLevel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Admin.
        /// </summary>
        public static string AddAdmin {
            get {
                return ResourceManager.GetString("AddAdmin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Player:.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh Players.
        /// </summary>
        public static string RefreshPlayers {
            get {
                return ResourceManager.GetString("RefreshPlayers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scans all server Guestbooks for known players.
        /// </summary>
        public static string ScanGuestbooks {
            get {
                return ResourceManager.GetString("ScanGuestbooks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manual entry (player not in list).
        /// </summary>
        public static string ManualEntry {
            get {
                return ResourceManager.GetString("ManualEntry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Epic ID:.
        /// </summary>
        public static string EpicIdLabel {
            get {
                return ResourceManager.GetString("EpicIdLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Match Mode.
        /// </summary>
        public static string MatchMode {
            get {
                return ResourceManager.GetString("MatchMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loadout Mode.
        /// </summary>
        public static string LoadoutMode {
            get {
                return ResourceManager.GetString("LoadoutMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GunGame.
        /// </summary>
        public static string GunGame {
            get {
                return ResourceManager.GetString("GunGame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ReverseGunGame.
        /// </summary>
        public static string ReverseGunGame {
            get {
                return ResourceManager.GetString("ReverseGunGame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KeepInventory.
        /// </summary>
        public static string KeepInventory {
            get {
                return ResourceManager.GetString("KeepInventory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Win Condition.
        /// </summary>
        public static string WinCondition {
            get {
                return ResourceManager.GetString("WinCondition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KillsToWin.
        /// </summary>
        public static string KillsToWin {
            get {
                return ResourceManager.GetString("KillsToWin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kills To Win.
        /// </summary>
        public static string KillsToWinLabel {
            get {
                return ResourceManager.GetString("KillsToWinLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Force Kill At Start.
        /// </summary>
        public static string ForceKillAtStart {
            get {
                return ResourceManager.GetString("ForceKillAtStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Heal On Kill.
        /// </summary>
        public static string HealOnKill {
            get {
                return ResourceManager.GetString("HealOnKill", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Heal Amount %:.
        /// </summary>
        public static string HealAmountPercent {
            get {
                return ResourceManager.GetString("HealAmountPercent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Drop Items On Death.
        /// </summary>
        public static string DropItemsOnDeath {
            get {
                return ResourceManager.GetString("DropItemsOnDeath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Can Go Down.
        /// </summary>
        public static string CanGoDown {
            get {
                return ResourceManager.GetString("CanGoDown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Can Lock Out.
        /// </summary>
        public static string CanLockOut {
            get {
                return ResourceManager.GetString("CanLockOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vote Settings.
        /// </summary>
        public static string VoteSettings {
            get {
                return ResourceManager.GetString("VoteSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Percent Of Votes.
        /// </summary>
        public static string PercentOfVotes {
            get {
                return ResourceManager.GetString("PercentOfVotes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Min Players.
        /// </summary>
        public static string MinPlayers {
            get {
                return ResourceManager.GetString("MinPlayers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Time To Start (seconds).
        /// </summary>
        public static string TimeToStartSeconds {
            get {
                return ResourceManager.GetString("TimeToStartSeconds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Spell Drops.
        /// </summary>
        public static string SpellDrops {
            get {
                return ResourceManager.GetString("SpellDrops", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Min Delay (seconds).
        /// </summary>
        public static string MinDelaySeconds {
            get {
                return ResourceManager.GetString("MinDelaySeconds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Max Delay (seconds).
        /// </summary>
        public static string MaxDelaySeconds {
            get {
                return ResourceManager.GetString("MaxDelaySeconds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First Drop Offset (seconds).
        /// </summary>
        public static string FirstDropOffsetSeconds {
            get {
                return ResourceManager.GetString("FirstDropOffsetSeconds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timeouts.
        /// </summary>
        public static string Timeouts {
            get {
                return ResourceManager.GetString("Timeouts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pre-Match Timeout (minutes).
        /// </summary>
        public static string PreMatchTimeoutMinutes {
            get {
                return ResourceManager.GetString("PreMatchTimeoutMinutes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Match Timeout (minutes).
        /// </summary>
        public static string MatchTimeoutMinutes {
            get {
                return ResourceManager.GetString("MatchTimeoutMinutes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Location Picker.
        /// </summary>
        public static string LocationPicker {
            get {
                return ResourceManager.GetString("LocationPicker", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apply Location.
        /// </summary>
        public static string ApplyLocation {
            get {
                return ResourceManager.GetString("ApplyLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ring Settings.
        /// </summary>
        public static string RingSettings {
            get {
                return ResourceManager.GetString("RingSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ring Sizes (3 values).
        /// </summary>
        public static string RingSizes {
            get {
                return ResourceManager.GetString("RingSizes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ring Speeds (3 values).
        /// </summary>
        public static string RingSpeeds {
            get {
                return ResourceManager.GetString("RingSpeeds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Closing (Deathmatch).
        /// </summary>
        public static string NoClosingDeathmatch {
            get {
                return ResourceManager.GetString("NoClosingDeathmatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Standard BR.
        /// </summary>
        public static string StandardBR {
            get {
                return ResourceManager.GetString("StandardBR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lobby Spawn.
        /// </summary>
        public static string LobbySpawn {
            get {
                return ResourceManager.GetString("LobbySpawn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Custom Spawn Point (x,y,z).
        /// </summary>
        public static string CustomSpawnPoint {
            get {
                return ResourceManager.GetString("CustomSpawnPoint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use Custom Spawn.
        /// </summary>
        public static string UseCustomSpawn {
            get {
                return ResourceManager.GetString("UseCustomSpawn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Match Spawns.
        /// </summary>
        public static string MatchSpawns {
            get {
                return ResourceManager.GetString("MatchSpawns", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Spawn Coordinates (one x,z per line):.
        /// </summary>
        public static string SpawnCoordinates {
            get {
                return ResourceManager.GetString("SpawnCoordinates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to StarterPack Fixes.
        /// </summary>
        public static string StarterPackFixes {
            get {
                return ResourceManager.GetString("StarterPackFixes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable Loot Drops.
        /// </summary>
        public static string EnableLootDrops {
            get {
                return ResourceManager.GetString("EnableLootDrops", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Grenades On Death - Attacker.
        /// </summary>
        public static string GrenadesOnDeathAttacker {
            get {
                return ResourceManager.GetString("GrenadesOnDeathAttacker", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Chance (0.0 - 1.0):.
        /// </summary>
        public static string ChanceLabel {
            get {
                return ResourceManager.GetString("ChanceLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Grenade:.
        /// </summary>
        public static string GrenadeLabel {
            get {
                return ResourceManager.GetString("GrenadeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Grenades On Death - Corpse.
        /// </summary>
        public static string GrenadesOnDeathCorpse {
            get {
                return ResourceManager.GetString("GrenadesOnDeathCorpse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lives &amp; Advanced.
        /// </summary>
        public static string LivesAndAdvanced {
            get {
                return ResourceManager.GetString("LivesAndAdvanced", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lives:.
        /// </summary>
        public static string LivesLabel {
            get {
                return ResourceManager.GetString("LivesLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (256 = infinite).
        /// </summary>
        public static string Lives256Infinite {
            get {
                return ResourceManager.GetString("Lives256Infinite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Streaming Distance:.
        /// </summary>
        public static string StreamingDistance {
            get {
                return ResourceManager.GetString("StreamingDistance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (-1 = normal).
        /// </summary>
        public static string StreamingDistanceDefault {
            get {
                return ResourceManager.GetString("StreamingDistanceDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ban List.
        /// </summary>
        public static string BanList {
            get {
                return ResourceManager.GetString("BanList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to One Epic ID per line.
        /// </summary>
        public static string OneEpicIdPerLine {
            get {
                return ResourceManager.GetString("OneEpicIdPerLine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Proximity Chat.
        /// </summary>
        public static string ProximityChat {
            get {
                return ResourceManager.GetString("ProximityChat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Max Range (m):.
        /// </summary>
        public static string MaxRangeM {
            get {
                return ResourceManager.GetString("MaxRangeM", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (default 50).
        /// </summary>
        public static string DefaultFifty {
            get {
                return ResourceManager.GetString("DefaultFifty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Min Range (m):.
        /// </summary>
        public static string MinRangeM {
            get {
                return ResourceManager.GetString("MinRangeM", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (default 5).
        /// </summary>
        public static string DefaultFive {
            get {
                return ResourceManager.GetString("DefaultFive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Falloff Curve:.
        /// </summary>
        public static string FalloffCurve {
            get {
                return ResourceManager.GetString("FalloffCurve", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Linear.
        /// </summary>
        public static string Linear {
            get {
                return ResourceManager.GetString("Linear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logarithmic.
        /// </summary>
        public static string Logarithmic {
            get {
                return ResourceManager.GetString("Logarithmic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loadout Mode:.
        /// </summary>
        public static string LoadoutModeLabel {
            get {
                return ResourceManager.GetString("LoadoutModeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import Raw.
        /// </summary>
        public static string ImportRaw {
            get {
                return ResourceManager.GetString("ImportRaw", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export Raw.
        /// </summary>
        public static string ExportRaw {
            get {
                return ResourceManager.GetString("ExportRaw", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loadouts.
        /// </summary>
        public static string LoadoutsHeader {
            get {
                return ResourceManager.GetString("LoadoutsHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Weight:.
        /// </summary>
        public static string WeightLabel {
            get {
                return ResourceManager.GetString("WeightLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        public static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Item:.
        /// </summary>
        public static string ItemLabel {
            get {
                return ResourceManager.GetString("ItemLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quantity:.
        /// </summary>
        public static string QuantityLabel {
            get {
                return ResourceManager.GetString("QuantityLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Curse Assignment.
        /// </summary>
        public static string CurseAssignment {
            get {
                return ResourceManager.GetString("CurseAssignment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blessing Assignment (added as items).
        /// </summary>
        public static string BlessingAssignment {
            get {
                return ResourceManager.GetString("BlessingAssignment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blessings are added as items to this loadout..
        /// </summary>
        public static string BlessingDescription {
            get {
                return ResourceManager.GetString("BlessingDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server Templates.
        /// </summary>
        public static string ServerTemplates {
            get {
                return ResourceManager.GetString("ServerTemplates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apply Template to Server.
        /// </summary>
        public static string ApplyTemplate {
            get {
                return ResourceManager.GetString("ApplyTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saved Presets:.
        /// </summary>
        public static string SavedPresets {
            get {
                return ResourceManager.GetString("SavedPresets", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Files to include when saving:.
        /// </summary>
        public static string FilesToInclude {
            get {
                return ResourceManager.GetString("FilesToInclude", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save current as new preset....
        /// </summary>
        public static string SaveCurrentPreset {
            get {
                return ResourceManager.GetString("SaveCurrentPreset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server Path.
        /// </summary>
        public static string ServerPath {
            get {
                return ResourceManager.GetString("ServerPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  [Client mod required].
        /// </summary>
        public static string ClientModRequired {
            get {
                return ResourceManager.GetString("ClientModRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Citruslib Tag:.
        /// </summary>
        public static string CitruslibTag {
            get {
                return ResourceManager.GetString("CitruslibTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Some selected plugins require matching client mods.
        /// </summary>
        public static string ClientModsNeeded {
            get {
                return ResourceManager.GetString("ClientModsNeeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select None.
        /// </summary>
        public static string SelectNone {
            get {
                return ResourceManager.GetString("SelectNone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sigma Preset.
        /// </summary>
        public static string SigmaPreset {
            get {
                return ResourceManager.GetString("SigmaPreset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installation Log.
        /// </summary>
        public static string InstallationLog {
            get {
                return ResourceManager.GetString("InstallationLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Continue without install.
        /// </summary>
        public static string ContinueWithoutInstall {
            get {
                return ResourceManager.GetString("ContinueWithoutInstall", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TABG Server Installer -- Setup.
        /// </summary>
        public static string SetupTitle {
            get {
                return ResourceManager.GetString("SetupTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome to TABG Server Installer.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First-time setup -- this only runs once..
        /// </summary>
        public static string WelcomeSubtitle {
            get {
                return ResourceManager.GetString("WelcomeSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Step 1: Server Path.
        /// </summary>
        public static string Step1Title {
            get {
                return ResourceManager.GetString("Step1Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select your TABG Dedicated Server folder..
        /// </summary>
        public static string Step1Description {
            get {
                return ResourceManager.GetString("Step1Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Step 2: Client Path (optional).
        /// </summary>
        public static string Step2Title {
            get {
                return ResourceManager.GetString("Step2Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select your TABG Steam folder for client mods..
        /// </summary>
        public static string Step2Description {
            get {
                return ResourceManager.GetString("Step2Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Step 3: Choose Starting Plugins.
        /// </summary>
        public static string Step3Title {
            get {
                return ResourceManager.GetString("Step3Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pick your initial server plugins..
        /// </summary>
        public static string Step3Description {
            get {
                return ResourceManager.GetString("Step3Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Step 4: Choose Starting Client Mods (optional).
        /// </summary>
        public static string Step4Title {
            get {
                return ResourceManager.GetString("Step4Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pick client-side mods for your modded TABG copy..
        /// </summary>
        public static string Step4Description {
            get {
                return ResourceManager.GetString("Step4Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        public static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Server.
        /// </summary>
        public static string AddServerTitle {
            get {
                return ResourceManager.GetString("AddServerTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Local Server.
        /// </summary>
        public static string LocalServer {
            get {
                return ResourceManager.GetString("LocalServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remote Server (SSH).
        /// </summary>
        public static string RemoteServerSsh {
            get {
                return ResourceManager.GetString("RemoteServerSsh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server Directory.
        /// </summary>
        public static string ServerDirectory {
            get {
                return ResourceManager.GetString("ServerDirectory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string BrowseEllipsis {
            get {
                return ResourceManager.GetString("BrowseEllipsis", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Private Key.
        /// </summary>
        public static string PrivateKey {
            get {
                return ResourceManager.GetString("PrivateKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remote Server Path.
        /// </summary>
        public static string RemoteServerPath {
            get {
                return ResourceManager.GetString("RemoteServerPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Process Mode:.
        /// </summary>
        public static string ProcessMode {
            get {
                return ResourceManager.GetString("ProcessMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Screen.
        /// </summary>
        public static string Screen {
            get {
                return ResourceManager.GetString("Screen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Systemd.
        /// </summary>
        public static string Systemd {
            get {
                return ResourceManager.GetString("Systemd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Server.
        /// </summary>
        public static string AddServer {
            get {
                return ResourceManager.GetString("AddServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update Now.
        /// </summary>
        public static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skip This Version.
        /// </summary>
        public static string SkipThisVersion {
            get {
                return ResourceManager.GetString("SkipThisVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remind Me Later.
        /// </summary>
        public static string RemindMeLater {
            get {
                return ResourceManager.GetString("RemindMeLater", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        public static string Servers {
            get {
                return ResourceManager.GetString("Servers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to + Add Server.
        /// </summary>
        public static string AddServerButton {
            get {
                return ResourceManager.GetString("AddServerButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server Path:.
        /// </summary>
        public static string ServerPathLabel {
            get {
                return ResourceManager.GetString("ServerPathLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Client Path:.
        /// </summary>
        public static string ClientPathLabel {
            get {
                return ResourceManager.GetString("ClientPathLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Modded TABG Path:.
        /// </summary>
        public static string ModdedTabgPathLabel {
            get {
                return ResourceManager.GetString("ModdedTabgPathLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hard Reset.
        /// </summary>
        public static string HardReset {
            get {
                return ResourceManager.GetString("HardReset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Completely reinstall the server from scratch..
        /// </summary>
        public static string HardResetDescription {
            get {
                return ResourceManager.GetString("HardResetDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hard Reset (Full Reinstall).
        /// </summary>
        public static string HardResetButton {
            get {
                return ResourceManager.GetString("HardResetButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Super Secret Settings.
        /// </summary>
        public static string SuperSecretSettings {
            get {
                return ResourceManager.GetString("SuperSecretSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        public static string Accessibility {
            get {
                return ResourceManager.GetString("Accessibility", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to High contrast mode.
        /// </summary>
        public static string HighContrastMode {
            get {
                return ResourceManager.GetString("HighContrastMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send anonymous crash reports.
        /// </summary>
        public static string SendCrashReports {
            get {
                return ResourceManager.GetString("SendCrashReports", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to When enabled, anonymous error details are sent to help improve the app..
        /// </summary>
        public static string CrashReportDescription {
            get {
                return ResourceManager.GetString("CrashReportDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restart the app to apply the language change..
        /// </summary>
        public static string RestartRequired {
            get {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This is password protected. Enter password to enter:.
        /// </summary>
        public static string PasswordProtected {
            get {
                return ResourceManager.GetString("PasswordProtected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Force Stop.
        /// </summary>
        public static string ForceStop {
            get {
                return ResourceManager.GetString("ForceStop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Item IDs.
        /// </summary>
        public static string ItemIDs {
            get {
                return ResourceManager.GetString("ItemIDs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Spawn Locations.
        /// </summary>
        public static string SpawnLocations {
            get {
                return ResourceManager.GetString("SpawnLocations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Match Settings Guide.
        /// </summary>
        public static string MatchSettingsGuide {
            get {
                return ResourceManager.GetString("MatchSettingsGuide", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Application Error.
        /// </summary>
        public static string CrashReportTitle {
            get {
                return ResourceManager.GetString("CrashReportTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The app encountered an error..
        /// </summary>
        public static string CrashReportPrompt {
            get {
                return ResourceManager.GetString("CrashReportPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only the error details and app version are sent..
        /// </summary>
        public static string CrashReportDetail {
            get {
                return ResourceManager.GetString("CrashReportDetail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes, Send Report.
        /// </summary>
        public static string YesSend {
            get {
                return ResourceManager.GetString("YesSend", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Thanks.
        /// </summary>
        public static string NoThanks {
            get {
                return ResourceManager.GetString("NoThanks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Always Send.
        /// </summary>
        public static string AlwaysSend {
            get {
                return ResourceManager.GetString("AlwaysSend", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Never Ask.
        /// </summary>
        public static string NeverAsk {
            get {
                return ResourceManager.GetString("NeverAsk", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Search plugins....
        /// </summary>
        public static string SearchPlugins {
            get {
                return ResourceManager.GetString("SearchPlugins", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update All.
        /// </summary>
        public static string UpdateAll {
            get {
                return ResourceManager.GetString("UpdateAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
    }
}
