//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabgInstaller.Gui.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tooltips {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tooltips() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TabgInstaller.Gui.Resources.Tooltips", typeof(Tooltips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to When enabled, items drop from loot containers..
        /// </summary>
        public static string LootDropsTooltip {
            get {
                return ResourceManager.GetString("LootDropsTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Also requires the client-side mod installed via the Client tab.
        /// </summary>
        public static string ClientModRequiredTooltip {
            get {
                return ResourceManager.GetString("ClientModRequiredTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select the plugins required for the CollinSigma preset.
        /// </summary>
        public static string SigmaPresetTooltip {
            get {
                return ResourceManager.GetString("SigmaPresetTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clone the selected loadout.
        /// </summary>
        public static string CloneLoadoutTooltip {
            get {
                return ResourceManager.GetString("CloneLoadoutTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type to search items across all categories.
        /// </summary>
        public static string SearchItemsTooltip {
            get {
                return ResourceManager.GetString("SearchItemsTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Double-click to add item.
        /// </summary>
        public static string DoubleClickAddTooltip {
            get {
                return ResourceManager.GetString("DoubleClickAddTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start the TABG dedicated server.
        /// </summary>
        public static string StartServerHelp {
            get {
                return ResourceManager.GetString("StartServerHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop the running server.
        /// </summary>
        public static string StopServerHelp {
            get {
                return ResourceManager.GetString("StopServerHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Launch the modded TABG client.
        /// </summary>
        public static string LaunchModdedHelp {
            get {
                return ResourceManager.GetString("LaunchModdedHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open the server installation folder in Explorer.
        /// </summary>
        public static string OpenServerFolderHelp {
            get {
                return ResourceManager.GetString("OpenServerFolderHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open the server log files.
        /// </summary>
        public static string OpenLogsHelp {
            get {
                return ResourceManager.GetString("OpenLogsHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open the server configuration files.
        /// </summary>
        public static string OpenConfigHelp {
            get {
                return ResourceManager.GetString("OpenConfigHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear all console output.
        /// </summary>
        public static string ClearConsoleHelp {
            get {
                return ResourceManager.GetString("ClearConsoleHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save current settings and restart the server.
        /// </summary>
        public static string QuickSaveRestartHelp {
            get {
                return ResourceManager.GetString("QuickSaveRestartHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filter console output by text.
        /// </summary>
        public static string SearchLogsHelp {
            get {
                return ResourceManager.GetString("SearchLogsHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export console output to a text file.
        /// </summary>
        public static string ExportLogsHelp {
            get {
                return ResourceManager.GetString("ExportLogsHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send a command to the server console.
        /// </summary>
        public static string SendCommandHelp {
            get {
                return ResourceManager.GetString("SendCommandHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Completely reinstall the server. Creates a backup first..
        /// </summary>
        public static string HardResetHelp {
            get {
                return ResourceManager.GetString("HardResetHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create a new backup of the current server state.
        /// </summary>
        public static string CreateBackupHelp {
            get {
                return ResourceManager.GetString("CreateBackupHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restore the selected backup to replace current server files.
        /// </summary>
        public static string RestoreBackupHelp {
            get {
                return ResourceManager.GetString("RestoreBackupHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Permanently delete the selected backup.
        /// </summary>
        public static string DeleteBackupHelp {
            get {
                return ResourceManager.GetString("DeleteBackupHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add a custom DLL plugin file.
        /// </summary>
        public static string AddDllHelp {
            get {
                return ResourceManager.GetString("AddDllHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove the selected item from the list.
        /// </summary>
        public static string RemoveSelectedHelp {
            get {
                return ResourceManager.GetString("RemoveSelectedHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh the current list.
        /// </summary>
        public static string RefreshHelp {
            get {
                return ResourceManager.GetString("RefreshHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open the folder in Explorer.
        /// </summary>
        public static string OpenFolderHelp {
            get {
                return ResourceManager.GetString("OpenFolderHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Install selected plugins or mods.
        /// </summary>
        public static string InstallSelectedHelp {
            get {
                return ResourceManager.GetString("InstallSelectedHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save current settings to file.
        /// </summary>
        public static string SaveSettingsHelp {
            get {
                return ResourceManager.GetString("SaveSettingsHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select the display language for the application.
        /// </summary>
        public static string LanguageHelp {
            get {
                return ResourceManager.GetString("LanguageHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable high contrast mode for better visibility.
        /// </summary>
        public static string HighContrastHelp {
            get {
                return ResourceManager.GetString("HighContrastHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send anonymous crash reports to help improve the application.
        /// </summary>
        public static string CrashReportHelp {
            get {
                return ResourceManager.GetString("CrashReportHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browse for the TABG server folder.
        /// </summary>
        public static string BrowseServerPathHelp {
            get {
                return ResourceManager.GetString("BrowseServerPathHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browse for the TABG Steam folder.
        /// </summary>
        public static string BrowseClientPathHelp {
            get {
                return ResourceManager.GetString("BrowseClientPathHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add a new local or remote server instance.
        /// </summary>
        public static string AddServerHelp {
            get {
                return ResourceManager.GetString("AddServerHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add the selected player as a server admin.
        /// </summary>
        public static string AddAdminHelp {
            get {
                return ResourceManager.GetString("AddAdminHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scan Guestbooks for known players.
        /// </summary>
        public static string RefreshPlayersHelp {
            get {
                return ResourceManager.GetString("RefreshPlayersHelp", resourceCulture);
            }
        }
    }
}
