<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\TabgInstaller.ProximityChat.Client\Libs\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>..\TabgInstaller.ProximityChat.Client\Libs\BepInEx.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\TabgInstaller.ProximityChat.Client\Libs\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\TabgInstaller.ProximityChat.Client\Libs\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\TabgInstaller.ProximityChat.Client\Libs\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\TabgInstaller.ProximityChat.Client\Libs\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TabgInstaller.ModSettings\TabgInstaller.ModSettings.csproj">
      <Private>False</Private>
    </ProjectReference>
  </ItemGroup>

  <Target Name="CopyEnhancedClientToBundledClientPlugins" AfterTargets="Build">
    <MakeDir Directories="$(MSBuildProjectDirectory)\..\bundled\client-plugins" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(MSBuildProjectDirectory)\..\bundled\client-plugins" SkipUnchangedFiles="true" />
  </Target>
</Project>
