<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <TabgClientManagedDir Condition="'$(TabgClientManagedDir)' == ''">$(MSBuildProjectDirectory)/Libs</TabgClientManagedDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="UnityEngine.AudioModule"><HintPath>../TabgInstaller.ProximityChat.Client/Libs/UnityEngine.AudioModule.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="0Harmony">
      <HintPath>Libs\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>Libs\BepInEx.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>Libs\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>Libs\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>Libs\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>Libs\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>Libs\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>Libs\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>Libs\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="UnityEngine.ParticleSystemModule"><HintPath>../TabgInstaller.CustomGrenades/Libs/UnityEngine.ParticleSystemModule.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="Sirenix.Serialization"><HintPath>../TabgInstaller.CustomGrenades/Libs/Sirenix.Serialization.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="EasyRoads3Dv3"><HintPath>$(TabgClientManagedDir)/EasyRoads3Dv3.dll</HintPath><Private>False</Private></Reference>
    <ProjectReference Include="..\TabgInstaller.ModSettings\TabgInstaller.ModSettings.csproj">
      <Private>False</Private>
    </ProjectReference>
  </ItemGroup>

  <Target Name="CopyFlyingControlsToBundledClientPlugins" AfterTargets="Build">
    <MakeDir Directories="$(MSBuildProjectDirectory)\..\bundled\client-plugins" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(MSBuildProjectDirectory)\..\bundled\client-plugins" SkipUnchangedFiles="true" />
  </Target>
  <ItemGroup>
    <Compile Include="../TabgInstaller.Vehicles.Shared/*.cs" Link="Shared/%(Filename)%(Extension)" />
  </ItemGroup>
<ItemGroup><EmbeddedResource Include="AudioAssets/*.wav"><LogicalName>TabgAudio.%(Filename)%(Extension)</LogicalName></EmbeddedResource></ItemGroup>
</Project>
